create table if not exists public.survey_responses (
 id bigint generated by default as identity primary key,
 player_name text not null default 'Anonymous' check (char_length(player_name) between 1 and 60),
 q1 text not null,
 q2 text not null,
 q3 integer check (q3 between 1 and 5),
 q4 text not null,
 q5 text default '',
 q6 text not null,
 q7 text not null,
 q8 text default '',
 created_at timestamptz not null default now()
);

alter table public.survey_responses enable row level security;

drop policy if exists "Public can submit survey" on public.survey_responses;
create policy "Public can submit survey" on public.survey_responses
for insert to anon, authenticated
with check (
 q1 in ('Daily','Few times a week','Rarely','Never')
 and q2 in ('Yes','No')
 and q3 between 1 and 5
 and q4 in ('Yes','No')
 and q6 in ('Yes','No','Unsure')
 and q7 in ('Yes','No')
);

drop policy if exists "Authenticated admins can view survey" on public.survey_responses;
create policy "Authenticated admins can view survey" on public.survey_responses
for select to authenticated using (true);

-- Create your private admin account in Supabase:
-- Authentication → Users → Add user.
-- Do NOT put the service_role key in the website.